#!/usr/bin/env python3
"""
generate_skills_manifest.py

Regenerates three artifacts from the frontmatter of every SKILL.md in the
agents skills directory (plus the Claude Code native command skills):

1. The auto generated skills manifest table in AGENTS.md, a cheap routing
   surface for agents without native skill discovery (such as Gemini CLI).
2. .agents/skills.json, a machine readable index (name, description,
   triggers, path) for any tool that wants the skill list without parsing
   markdown.
3. .claude/skills/, rebuilt as a real directory of per-entry symlinks (one
   per domain skill in .agents/skills/, one per Claude-Code-native command
   skill in .agents/skill_commands/), so Claude Code discovers both from
   inside this repo, and scripts/install_global.sh/.ps1 can glob individual
   entries to link them globally on other machines.

Output is deterministic (no timestamps), so reruns without skill changes
produce no diff. Runs automatically from the pre-commit hook installed by
scripts/install_pre_commit_hook.py, or manually:
    python scripts/generate_skills_manifest.py
"""

import json
import os
import sys

_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, _root)
sys.path.insert(0, os.path.join(_root, "src"))

from howlplane.control_plane.skill_router import SkillRouter  # noqa: E402
from howlplane.control_plane.config_loader import default_loader  # noqa: E402

MANIFEST_START = "<!-- SKILLS_MANIFEST_START -->"
MANIFEST_END = "<!-- SKILLS_MANIFEST_END -->"


def build_manifest_table(skills) -> str:
    """Renders the skills as a markdown table."""
    lines = [
        MANIFEST_START,
        "| Skill | Tier | Description | Path |",
        "| --- | --- | --- | --- |",
    ]
    repo_root = default_loader.get_repo_root()
    for skill in skills:
        rel_path = os.path.relpath(skill.path, repo_root)
        description = skill.description.replace("|", "\\|")
        tier = skill.tier if skill.tier is not None else ""
        lines.append(f"| {skill.name} | {tier} | {description} | `{rel_path}` |")
    lines.append(MANIFEST_END)
    return "\n".join(lines)


def update_agents_md(agents_md_path: str, table: str) -> None:
    """Replaces the manifest block in AGENTS.md, or appends a new section."""
    with open(agents_md_path, "r", encoding="utf8") as f:
        content = f.read()

    if MANIFEST_START in content and MANIFEST_END in content:
        start = content.index(MANIFEST_START)
        end = content.index(MANIFEST_END) + len(MANIFEST_END)
        content = content[:start] + table + content[end:]
    else:
        section = (
            "\n## Skills Manifest\n\n"
            "Auto generated by `scripts/generate_skills_manifest.py`. "
            "Do not edit by hand. Consult the listed SKILL.md file whenever a "
            "task matches a skill's description.\n\n"
        )
        content = content.rstrip("\n") + "\n" + section + table + "\n"

    with open(agents_md_path, "w", encoding="utf8") as f:
        f.write(content)


def write_skills_index(skills, index_path: str) -> None:
    """Writes the machine readable skills index as JSON."""
    repo_root = default_loader.get_repo_root()
    index = {
        "version": 1,
        "skills": [
            {
                "name": skill.name,
                "description": skill.description,
                "triggers": skill.triggers,
                "tier": skill.tier,
                "path": os.path.relpath(skill.path, repo_root),
            }
            for skill in skills
        ],
    }
    with open(index_path, "w", encoding="utf8") as f:
        json.dump(index, f, indent=2)
        f.write("\n")


def sync_claude_skills_dir(repo_root: str) -> None:
    """
    Rebuilds .claude/skills/ as a real directory of per-entry symlinks: one
    per domain skill in .agents/skills/, one per Claude-Code-native command
    skill in .agents/skill_commands/. Replaces the older single directory
    level symlink (.claude/skills -> ../.agents/skills), which could not
    also expose .agents/skill_commands/ alongside it.
    """
    target_dir = os.path.join(repo_root, ".claude", "skills")

    if os.path.islink(target_dir):
        os.remove(target_dir)
    if not os.path.isdir(target_dir):
        os.makedirs(target_dir)
    else:
        for entry in os.listdir(target_dir):
            entry_path = os.path.join(target_dir, entry)
            if os.path.islink(entry_path):
                os.remove(entry_path)

    sources = (
        (os.path.join(repo_root, ".agents", "skills"), os.path.join("..", "..", ".agents", "skills")),
        (
            os.path.join(repo_root, ".agents", "skill_commands"),
            os.path.join("..", "..", ".agents", "skill_commands"),
        ),
    )
    for source_dir, rel_prefix in sources:
        if not os.path.isdir(source_dir):
            continue
        for entry in sorted(os.listdir(source_dir)):
            if not os.path.isdir(os.path.join(source_dir, entry)):
                continue
            link_path = os.path.join(target_dir, entry)
            if os.path.lexists(link_path):
                os.remove(link_path)
            os.symlink(os.path.join(rel_prefix, entry), link_path)


def main():
    router = SkillRouter()
    if not router.skills:
        print(f"No skills found in {router.skills_dir}. Nothing to do.")
        sys.exit(1)

    repo_root = default_loader.get_repo_root()

    agents_md_path = os.path.join(repo_root, "AGENTS.md")
    table = build_manifest_table(router.skills)
    update_agents_md(agents_md_path, table)
    print(f"Wrote manifest with {len(router.skills)} skills to {agents_md_path}")

    index_path = os.path.join(repo_root, ".agents", "skills.json")
    write_skills_index(router.skills, index_path)
    print(f"Wrote skills index to {index_path}")

    sync_claude_skills_dir(repo_root)
    print(f"Synced Claude Code skill symlinks in {os.path.join(repo_root, '.claude', 'skills')}")


if __name__ == "__main__":
    main()
